#!/usr/bin/env python3.11
import os
import re
import sys


def main():
    file_path = os.getenv('DOCUMENT_URI')
    file_path = file_path.replace("/read/", "", 1)
    if not re.match(r'^[0-9a-fA-F]+\.wmap$', file_path):
        print("Status: 400 Bad Request")
        print("Cache-Control: public, max-age=31536000")
        print("Content-Type: text/plain")
        print("")
        print("This file does not exist on this host")
        return

    file_path = f"/var/www/htdocs/wmap/{file_path}"
    
    # Check if the file exists
    if not os.path.isfile(file_path):
        print("Status: 404 Not Found")
        print("Cache-Control: no-store")
        print("Content-Type: text/plain")
        print("")
        print("This file does not exist on this host")
        return

    try:
        # Open and read the file in chunks
        with open(file_path, 'r') as file:
            print("Status: 200 OK")
            print("Cache-Control: public, max-age=31536000")
            print("Content-Type: application/json")
            print("")
            while True:
                chunk = file.read(4096)  # Read in 4096-byte chunks
                if not chunk:
                    break
                print(chunk, end='')
    except Exception as e:
        print(f"Error: An error occurred while reading the file '{file_path}': {e}", file=sys.stderr)


if __name__ == "__main__":
    main()
