name: Lint and Test

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  test-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Run Tests
      run: make test
  test-macos:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v4
    - name: Install Terraform
      run: |
        brew tap hashicorp/tap
        brew install hashicorp/tap/terraform
    - name: Run Tests
      run: make test
