name: Makefile CI

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: runner.invalid

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make
