name: Lint and Test

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    steps:
    - uses: actions/checkout@v4
    - run: make test

  macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, macos-13, macos-14]
    steps:
    - uses: actions/checkout@v4
    - name: Install Terraform
      run: |
        brew tap hashicorp/tap
        brew install hashicorp/tap/terraform
    - run: make test
